DATASET:
  root_dataset: "./data/predict_friction"
  list_train: "./data/predict_friction/train"
  list_val: "./data/predict_friction/val"
  img_size: (256, 256)
  buffer_size: 3
  num_classes: 2

MODEL:
  optical_flow: "farneback"
  perceptual: "resnet18"
  include_images: False
  include_optical_flow: True

TRAIN:
  batch_size_per_gpu: 8
  num_epoch: 5
  start_epoch: 0
  epoch_iters: 10
  optim: "SGD"
  lr_perceptual: 0.1
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  workers: 8
  disp_iter: 20
  seed: 304

VAL:
  visualize: False
  checkpoint: "epoch_5.pth"

TEST:
  checkpoint: "epoch_5.pth"
  result: "./results"

DIR: "ckpt/optical_flow_only-predict_friction-farneback-resnet18-pybullet"