DATASET:
  root_dataset: "./data/same_vis_same_phys"
  list_train: "./data/same_vis_same_phys/train"
  list_val: "./data/same_vis_same_phys/val"
  imgSize: (256, 256)
  bufferSize: 3

MODEL:
  optical_flow: "spynet"
  perceptual: "resnet18"

TRAIN:
  batch_size_per_gpu: 1
  num_epoch: 5
  start_epoch: 0
  epoch_iters: 80
  optim: "SGD"
  lr_perceptual: 0.02
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  workers: 8
  disp_iter: 20
  seed: 304

VAL:
  visualize: False
  checkpoint: "epoch_20.pth"

TEST:
  checkpoint: "epoch_20.pth"
  result: "./"

DIR: "ckpt/same_vis_same_phys-spynet-resnet18-pybullet"